export const RETRIEVE_PAISES = "RETRIEVE_PAISES";
export const CREATE_PAISES = "CREATE_PAISES";
export const UPDATE_PAISES = "UPDATE_PAISES";
export const DELETE_PAISES = "DELETE_PAISES";
export const DETAILS_PAISES = "DETAILS_PAISES";
export const CREATE_USUARIO = "CREATE_USUARIO";
export const CHECK_USUARIO = "CHECK_USUARIO";
export const CHECK_USUARIO_UNO = "CHECK_USUARIO_UNO";
